### ISSUE TITLE
Data Registry Sidebar Icon

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab-data-explorer#111]
I got really tired of the green datagrid icon we're using so I spent some time on a better Icon. The finalists are listed below. 
![Screen Shot 2019-10-24 at 5 00 23 PM](https://user-images.githubusercontent.com/22109376/67533799-234ce700-f680-11e9-91ba-26357b4fba35.png)
I like the idea of the server and the and the magnifying glass. The folder is around because of the functionality here. It's a lot like the file browser so making it look like the file browser makes sense to me. Having just the folder with the server on it may be simple enough to work.

**Comment by saulshanabrook** [comment]
Yay! I like the right two the best, with the magnifying glass overlayed on the server. I actually like the one with all three the best I think.

**Comment by kgryte** [comment]
Of these, the ones on the far right.

**Comment by tgeorgeux** [comment]
It makes sense to me to show the folder as well, especially given the discussion last friday of how we may integrate this into the file browser eventually.
