### ISSUE TITLE
Missing datasets schema file

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-data-explorer#119]
It looks like the datasets schema file was removed in a refactor:

https://github.com/jupyterlab/jupyterlab-data-explorer/blob/aff047f698ecbd40af7cc936f7b45e54abb1e4b3/packages/dataregistry-extension/src/file.ts#L40

We should find it in the history and re-add it to that package.

**Comment by kgryte** [comment]
@saulshanabrook Doesn't that file get generated during the build?

**Comment by kgryte** [comment]
See [here](https://github.com/jupyterlab/jupyterlab-data-explorer/blob/aff047f698ecbd40af7cc936f7b45e54abb1e4b3/packages/dataregistry-extension/package.json#L31).

**Comment by saulshanabrook** [comment]
Ah yeah, thanks. Brain fart.

**Comment by saulshanabrook** [comment]
This is why you shouldn't try to be to clever I guess!
