### ISSUE TITLE
Paths with spaces not working

### ISSUE THREAD

**Issue by flutefreak7** [jupyterlab/jupyterlab-data-explorer#132]
## Description

> Description of the issue.

When I click "show" under a folder name that includes a space the UI says `loading...` but it never loads. The spaces appear as `%20` in the Datasets file browser. The JupyterLab terminal shows the following error on an example folder `/Admin/Org Charts`:

```
[W 11:07:54.040 LabApp] 404 GET /api/contents/Admin/Org%2520Charts?1576084074036 (::1): No such file or directory: Admin/Org%20Charts
[W 11:07:54.041 LabApp] No such file or directory: Admin/Org%%20Charts
[W 11:07:54.041 LabApp] 404 GET /api/contents/Admin/Org%2520Charts?1576084074036 (::1) 1.00ms referer=http://localhost:8888/lab
```

#### Environments

> What environments are affected (e.g., if unique to a particular browser, `Chrome`, `IE 11`)? Include the Python package version, extension version, and any other potentially relevant platform information.

The following environments are affected:

-   Device: Dell Laptop
-   OS: Windows 10
-   Browser: Chrome
-   JupyterLab version: 1.0.5
-   dataregistry-extension version: 3.0.0

**Comment by saulshanabrook** [comment]
Hey @flutefreak7 thanks for opening this! Yep, I have hit this a bunch of times so far...
