### ISSUE TITLE
Installing the plugin failed

### ISSUE THREAD

**Issue by alanchuangi** [jupyterlab/jupyterlab-data-explorer#134]
OS: win10 build 18362 356

I can't install jupyterlab-data-explorer successfully after type this command
jupyter labextension install @jupyterlab/dataregistry-extension

Could any friend touched  this issue before?

that is the full log for everyone reference

https://pastebin.com/JjT0H0yx

**Comment by saulshanabrook** [comment]
@alanchuangi If you just run `jupyter lab build` does the same error occur?
