### ISSUE TITLE
Support JupyterLab 3.0

### ISSUE THREAD

**Issue by ChrisCarini** [jupyterlab/jupyterlab-data-explorer#143]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-- **Similar:** #138 - [Support JupyterLab 2.1](https://github.com/jupyterlab/jupyterlab-data-explorer/issues/138)

## Description

> Description of the feature request.

This feature request proposes adding support for JupyterLab 3.0.

## Related Issues

> Does this feature request have any related issues?

Related issues #138 ([Support JupyterLab 2.1](https://github.com/jupyterlab/jupyterlab-data-explorer/issues/138))..

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

JupyterLab 3.0 was released on 2021-01-05 -> https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb

### Error Output
```
ValueError: The extension "@jupyterlab/dataregistry-extension" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=3.0.9 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/application
>=3.0.7 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/apputils
>=5.0.5 <5.1.0          >=3.0.0 <4.0.0   @jupyterlab/coreutils
>=3.0.9 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/docmanager
>=3.0.9 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/filebrowser
>=3.0.9 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/notebook
>=3.0.8 <3.1.0          >=1.0.0 <2.0.0   @jupyterlab/rendermime
>=17.0.1 <18.0.0        16.8.4           react
```

[code-of-conduct]: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md

**Comment by gepcel** [comment]
Seems that neither data-explorer extension for jupyterlab nor [data-explorer](https://atom.io/packages/data-explorer) for atom works anymore.
