### ISSUE TITLE
Data explorer overview

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-data-explorer#3]
This issue provides an overview of the roadmap of the data explorer. 

## Background

The JupyterLab data registry will enable extensions to 1) register abstract datasets with a central service and 2) monitor the registry for datasets. The dataset abstraction in the data registry includes:

* Text-based MIME type
* Optional URI to point at datasets that are persistent
* Abstract dataset pointer

The data registry also includes a converter architecture that can convert datasets from one MIME type to another.

Conceptually, the data registry will make datasets a first class entity or **noun** in JupyterLab.

## Data explorer UI

The Data explorer is a proposed user interface to enable users to explore datasets that different extensions have registered with the registry, and the do interesting things with the datasets, such as:

* Render them using MIME renderers.
* Comment on and annotate the datasets.
* Create and view metadata attached to the datasets.

Conceptually, the data explorer UI will provide a user interface for the **verbs** related to a dataset, or the actions or activities a users can perform with the dataset, such as "render this as a table".

## Initial design thoughts

* Probably a left sidebar based UI as this is similar to others currently there with an "overview" or "explore" idea.
* A list a datasets.
* For each dataset a discoverable list of things you can do with the dataset:
  - MIME renderers.
  - Create/edit metadata.
  - Open comments for the dataset.
* The metadata and commenting/annotation UIs will likely rely on another extension being developed separately.
* We may also want extension points to register new "things you can do" for a given MIME type.
* We will want to take into account the MIME type of the dataset, but also the different MIME types that can be created through the converter API.

The visual representation of the list of datasets, and the things you can do with them is still a core design question.

@saulshanabrook @tgeorgeux

**Comment by saulshanabrook** [comment]
I am closing this for now, since we have some initial UI developed.
