### ISSUE TITLE
Fix dissapearing nteract Data Explorer after a second

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-data-explorer#58]

**Comment by springuper** [comment]
I noticed this issue as well, whenever clicking a chart icon in the Data Explorer tab, after a second, the following error happens and the tab becomes white:

<img width="932" alt="Screen Shot 2019-10-25 at 5 07 07 PM" src="https://user-images.githubusercontent.com/687412/67558698-0b419a00-f74a-11e9-9355-38a792af1539.png">

React says: `Objects are not valid as a React child`.
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=Thu%20Jan%2001%201970%2008%3A00%3A00%20GMT%2B0800%20(China%20Standard%20Time)&args[]=
