### ISSUE TITLE
User Needs Analysis & User Stories

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab-data-explorer#6]
We had an in-person meeting contributors from NYU and Project Jupyter to define the User Needs for the Data Explorer project. Please keep in mind, it's still a work in progress, and I'll be updating this thread as we have more finalized, but I wanted to open this up for wider input in the meantime. The working document is available at: [Dataset Explorer: User Needs Analysis](https://docs.google.com/document/d/1Tjfg-PY91ufjuMcQAWMgigtcHf5UI0m4EwRQBUkYrrw/edit?usp=sharing)

## Why would somebody use a data explorer?

- To see a list of the datasets they have opened in JupyterLab or which someone has made available to them through the data registry. 
- Organize and collate groups of data sets for multi-user projects. 
- Social usages of data. 
- Cross-reference related usages of Data sets. 
- Provide suggestions/recommendations of other datasets that are relevant to their work. 
- To see different things they can do with those data sets. 
- To render the data sets using different visual representations (visualization, table, graph, etc.). 
- To view and edit metadata on datasets. 
- To encourage people to discuss and produce code snippets for data sets. 
- To explore data sets available to them for a pre-specified project. 
- Give a ‘sneak peak’ of data sets. 
- Browsing datasets by metadata (such as publisher, related datasets, dataset catalogue, etc.). 
- So they can push cleaned data back to the administrator to update the registry.
- To share insights between projects.

## Touch Points
Users will often use the Data Explorer:
- At the beginning of a project to explore relevant data sets.
- After they’ve imported (registered) the data sets relevant to the project. (Phase II)
- During work on the project, as new areas of interest arise, researchers will be looking for data to operationalize and integrate these additional areas of interest.
- After they’ve been working on the project for a while and want to review data sets. 
- At project wrap up, to confirm their data sets have been used properly.
- While they are working with a data-set. 

## Relevant Personas
Joe Data Scientist (PI) - Has domain expertise, writes a lot of code. 

Jane Data Set Administrator - Works with her developers to register correct datasets along with relevant metadata/comments/code snippets. 

Mike Business intelligence analyst - Is doing similar tasks to Data Scientist but doesn’t write so much code. 

### Phase I

- Extensions should register dataset that the user already has approved access to, and which are considered “actively used” by the user.
- Assume number of registered datasets is small (<10).

### Phase II

- Data registry gains notion of different classes of datasets, such as active, available, request access.
- Along with this, the UI/UX would need to modified to address the many dataset usage case (100s-1000s). Search, and namespaces would become important.

**Comment by saulshanabrook** [comment]
Closing this for now, happy to reopen it if we have some actionable steps here.

**Comment by tgeorgeux** [comment]
I've re-opened this issue to track User Stories for the path to handoff for this project. Below are the user Stories, we should separate these into phase I and Phase II and I'll provide user flow prototypes for each feature addressed.

- Register
    - As an Analyst, I want to register a dataset to a project, so I can find it later when I need it.
        - Datasets I always knew I wanted.
        - Datasets I just learned I wanted.
        - Sub-sets of already registered datasets.
    - As a Steward I want to give analysts access to datasets related to a project, so they can get started.
    - When I registers data, I want to orginize it into projects, so I can access datasets in context.
    - When I have an interesting cell output I want to register it, so I can review it later.
    - When I locate a file that contains useful data I want to add it to the registry so I can access it easily.
- Browse
    - As an analyst I want to see all the files related to a project, so I can start analysis.
    - When I find interesting datasets I want to register it to a project, so I don't have to search for it later. 
- Expand/Collapse
    - When I have nested datasets I want to access the organization so I can pick sub-sets
    - When I am working in a project, I want to see only the data associated with the project, so I dont' get distracted.
- Inspect
    - When I find interesting datasets I want see what activities in Jupyterlab they are compatible with, so I can explore in depth.
    - When I find a useful dataset, I want to see other related datasets (link to knowledge graph)
    - When I browse the Data Registry, I want to view dataset details. (Metadata graph, file/dataset details)
