### ISSUE TITLE
Clean up data browser UI

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-data-explorer#69]
* Pin to right hand side
* Preserve viewer in settings

**Comment by telamonian** [comment]
ooo, and a collapse-all button would be really nice. Basically just a way to "reset" without having to scroll all the way to the top

**Comment by saulshanabrook** [comment]
Ah good idea! I took a look at trying to reuse the existing tree file browser extension you showed me, but it's pretty tied to the current model and isn't implemented in React.

**Comment by saulshanabrook** [comment]
Fixed these in https://github.com/jupyterlab/jupyterlab-data-explorer/pull/71
