### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by alligator999** [jupyterlab/jupyterlab-data-explorer#78]
I Can`t install on Ubuntu. Environment managed by conda.

(base) user@ubuntu-VirtualBox:~/workplace$ jupyter labextension install @jupyterlab/dataregistry
An error occured.
ValueError: "@jupyterlab/dataregistry" is not a valid extension:
No `jupyterlab` key
See the log file for details:  /tmp/jupyterlab-debug-tt_jzsjs.log

cat /tmp/jupyterlab-debug-tt_jzsjs.log
Node v11.14.0

> /home/rafal/anaconda3/bin/npm pack @jupyterlab/dataregistry
npm notice
npm notice 📦  @jupyterlab/dataregistry@2.0.0
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 1.6kB lib/cachedObservable.d.ts
npm notice 3.7kB lib/cachedObservable.js
npm notice 2.6kB lib/cachedObservable.js.map
npm notice 867B  lib/converters.d.ts
npm notice 1.3kB lib/converters.js
npm notice 1.2kB lib/converters.js.map
npm notice 3.0kB lib/datasets.d.ts
npm notice 2.8kB lib/datasets.js
npm notice 1.1kB lib/datasets.js.map
npm notice 2.6kB lib/datatypes.d.ts
npm notice 3.6kB lib/datatypes.js
npm notice 3.1kB lib/datatypes.js.map
npm notice 788B  lib/files.d.ts
npm notice 1.1kB lib/files.js
npm notice 1.1kB lib/files.js.map
npm notice 789B  lib/folders.d.ts
npm notice 1.2kB lib/folders.js
npm notice 1.3kB lib/folders.js.map
npm notice 747B  lib/index.d.ts
npm notice 780B  lib/index.js
npm notice 348B  lib/index.js.map
npm notice 11B   lib/index.test.d.ts
npm notice 2.5kB lib/index.test.js
npm notice 3.0kB lib/index.test.js.map
npm notice 1.4kB lib/nested.d.ts
npm notice 1.5kB lib/nested.js
npm notice 703B  lib/nested.js.map
npm notice 673B  lib/registry.d.ts
npm notice 1.4kB lib/registry.js
npm notice 1.6kB lib/registry.js.map
npm notice 584B  lib/resolvers.d.ts
npm notice 838B  lib/resolvers.js
npm notice 698B  lib/resolvers.js.map
npm notice 296B  lib/testutils.d.ts
npm notice 804B  lib/testutils.js
npm notice 826B  lib/testutils.js.map
npm notice 718B  lib/urls.d.ts
npm notice 1.5kB lib/urls.js
npm notice 1.5kB lib/urls.js.map
npm notice 668B  lib/utils.d.ts
npm notice 1.4kB lib/utils.js
npm notice 1.6kB lib/utils.js.map
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/dataregistry
npm notice version:       2.0.0
npm notice filename:      jupyterlab-dataregistry-2.0.0.tgz
npm notice package size:  15.6 kB
npm notice unpacked size: 61.2 kB
npm notice shasum:        5f4b8e4acdae3a37812d0fa5fabbaee8dec0b93c
npm notice integrity:     sha512-Ksie4BJ8AzUvh[...]3UEgEzr/kftdg==
npm notice total files:   43
npm notice
jupyterlab-dataregistry-2.0.0.tgz

Traceback (most recent call last):

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/rafal/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1380, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))

ValueError: "@jupyterlab/dataregistry" is not a valid extension:
No `jupyterlab` key

Exiting application: jupyter

**Comment by saulshanabrook** [comment]
Can you try installing `@jupyterlab-dataregistry-extension`? Out of curiosity, why did you try to install the non extension package? You are the second person who has done this and had issues. Is there a place we could make this clearer in the docs?

**Comment by alligator999** [comment]
I used instruction from https://github.com/jupyterlab/jupyterlab-data-explorer#jupyterlab-data-explorer--- 
:)
![image](https://user-images.githubusercontent.com/35902744/64188590-fe53a900-ce72-11e9-82e7-47208ff02d84.png)

**Comment by vidartf** [comment]
https://github.com/jupyterlab/jupyterlab-data-explorer/pull/81
