### ISSUE TITLE
Add User Facing Docs

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-data-explorer#86]
We should separate out the current developer facing documentation in the README into a separate file, and add more user facing contents to the README. To say things like "This is what you should see in  the UI and how to navigate it. If you add a converter, it will show up here"

**Comment by tgeorgeux** [comment]
Outline
- Intro to Data explorer
    - Notable Use Cases (User Stories)
        - Find a dataset you want to use and launch it.
        - Select a cell and see another view and register as a dataset.
        - Find the dataset you want
            - Browse S3 buckets, All your notebooks, or your companies data catalog
        - Access alternate views of your datasets
    - Using the data explorer
        - What is a dataset? (everything is a dataset)
             - In order for the data explorer to recognize a dataset, it must have a URI and contain data in a recognizable format.
             - Data explorer automatically displays children and surfaces activities based on what you can do in Jupyterlab with that dataset.
            - Navigating nested data (left panel)
            - Launching Activities (left panel)
            - Surfacing Metadata (right panel), can surface data inspector from data explorer or from any relevant activity in Jupyterlab.
        - Link out to full developer docs
